### ISSUE TITLE
renga status fails after an update

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renga-python#157]
running `renga status` after a `renga update` results in:

```
renga status
Traceback (most recent call last):
  File "/Users/rok/Projects/renga-python/renga/cli/_graph.py", line 177, in add_tool
    tool = CommandLineTool.from_cwl(cwl)
  File "/Users/rok/Projects/renga-python/renga/models/cwl/_ascwl.py", line 39, in from_cwl
    'Got {0} but need {1}'.format(class_name, cls.__name__)
TypeError: Got Workflow but need CommandLineTool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rok/.virtualenvs/renga-demo/bin/renga", line 11, in <module>
    load_entry_point('renga', 'console_scripts', 'renga')()
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/rok/.virtualenvs/renga-demo/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/rok/Projects/renga-python/renga/cli/status.py", line 38, in status
    status = graph.build_status(revision=revision)
  File "/Users/rok/Projects/renga-python/renga/cli/_graph.py", line 315, in build_status
    self.add_file(filepath, revision=revision)
  File "/Users/rok/Projects/renga-python/renga/cli/_graph.py", line 223, in add_file
    self.add_tool(commit, cwl, file_key=file_key)
  File "/Users/rok/Projects/renga-python/renga/cli/_graph.py", line 181, in add_tool
    commit, path, file_key=file_key, cwl=cwl
  File "/Users/rok/Projects/renga-python/renga/cli/_graph.py", line 140, in add_workflow
    self.G.add_edge(input_map[source], tool_key, id=input_id)
KeyError: 'step_1/output_stdout'
```

**Comment by jirikuncar** [comment]
It seems like you have run the older version of the code. See https://github.com/SwissDataScienceCenter/renga-python/blob/development/renga/cli/_graph.py#L176-L183
